# Generated by Django 2.1.7 on 2020-01-23 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=None, null=True)),
                ('total_person', models.IntegerField(default=1, error_messages={'blank': 'Total person field may not be blank.', 'required': 'Total person is required.'})),
                ('is_invited', models.BooleanField(default=None, null=True)),
                ('is_ticket', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=30, unique=True)),
                ('invite_type', models.CharField(default=None, max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_doctors', to='doctors.Doctors'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_patients', to='patients.Patients'),
        ),
    ]
