# Generated by Django 2.1.7 on 2020-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='invite_type',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='is_ticket',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='token',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='total_person',
        ),
        migrations.AddField(
            model_name='appointments',
            name='message',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='addr',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialised',
            field=models.CharField(default='PATIENT', max_length=15),
        ),
    ]
