# Generated by Django 2.1.7 on 2020-01-23 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20200123_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
