# Generated by Django 3.0 on 2020-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20200124_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specilaizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=200)),
            ],
        ),
    ]
